# Generated by Django 4.1.2 on 2023-02-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_activity_imagefour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('discreption', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='rolle',
            field=models.CharField(choices=[('بەرێوبەر', 'بەرێوبەر'), ('ئیدارە', 'ئیدارە'), ('مامۆستا', 'مامۆستا'), ('یاریدەدەری بەرێوبەر', 'یاریدەدەری بەرێوبەر')], default='مامۆستا', max_length=100),
        ),
    ]
