# Generated by Django 4.1.2 on 2023-02-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_alter_team_rolle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='discreption',
            new_name='message',
        ),
    ]
