# Generated by Django 4.1.2 on 2023-03-19 07:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_discreption_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='discreption',
            field=tinymce.models.HTMLField(),
        ),
    ]
